version: '3.8'
services:
  jenkins:
    build: 
      context: .
      dockerfile: .docker/Jenkins/Dockerfile
    image: jenkins-jdk-21
    container_name: jenkins-jdk-21
    user: root
    restart: always
    environment:
      - JENKINS_HOME=/root/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/root/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-agent-ssh-key:/var/jenkins-agent-ssh-key:ro
    networks:
      - jenkins-network

  jenkins-agent:
    build: 
      context: .
      dockerfile: .docker/Agent/Dockerfile
    image: jenkins-ssh-agent-jdk-21
    container_name: jenkins-ssh-agent
    hostname: jenkins-agent
    user: root
    ports:
      - "2200:22"
    volumes:
      - jenkins-ssh-agent:/home/jenkins/agent
      - jenkins-agent-ssh-host-keys:/etc/ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${JENKINS_AGENT_SSH_PUBKEY:?missing_jenkins_agent_ssh_pubkey}"
    networks:
      - jenkins-network



volumes:
  jenkins_home:
    name: jenkins_home
  jenkins-ssh-agent:
    name: jenkins-ssh-agent
  jenkins-agent-ssh-host-keys:
    name: jenkins-agent-ssh-host-keys

networks:
  jenkins-network:
    name: jenkins-network
    
